### ISSUE TITLE
UML, diagramme d'utilisation : même erreur que groupe Humbert

### ISSUE THREAD

**Issue by droumanet** [Obituary-Dev/Asimov#3]
Dans la modélisation, un cas d'utilisation **inclut** signifie qu'il faut obligatoirement le faire pour pouvoir créer un élève... c'est une erreur (et un schéma) que j'ai déjà vu sur le projet de Lucas...
![image](https://user-images.githubusercontent.com/24438463/115989528-1aafd680-a5bf-11eb-9edc-9b1129d23088.png)

Supprimer est un cas d'utilisateur qui doit être relié au rôle (de même que modifier)

**Comment by Obituary-Dev** [comment]
Par conséquent, pour dire que créer des élèves induit qu'on peut les supprimer ou les modifier, comment je pourrais le modéliser ?

**Comment by droumanet** [comment]
Au plus simple : 
![image](https://user-images.githubusercontent.com/24438463/115992981-b85fd180-a5d0-11eb-8610-f55f72d046d8.png)

**Comment by Obituary-Dev** [comment]
Yes je viens de corriger, plus de include
